#!/bin/bash
# ============================================================================
# View1 Studio — Mac Mini Bootstrap Script
# Run this ONCE on the Mac Mini to set up autonomous production.
# After this, control everything from Telegram.
#
# Usage:
#   chmod +x mac-mini-bootstrap.sh
#   ./mac-mini-bootstrap.sh
#
# Prerequisites:
#   - macOS with Homebrew (or will install it)
#   - GitHub PAT with repo scope (will prompt)
#   - Telegram bot token + chat ID (will prompt)
#   - Anthropic API key (will prompt)
# ============================================================================

set -e

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  View1 Studio — Mac Mini Autonomous Setup               ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Install system dependencies ──────────────────────────────────────

echo "▸ Step 1/7: Installing system dependencies..."

if ! command -v brew &>/dev/null; then
  echo "  Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
fi

for tool in node git tmux gh jq; do
  if ! command -v $tool &>/dev/null; then
    echo "  Installing $tool..."
    brew install $tool
  else
    echo "  ✓ $tool already installed"
  fi
done

# Claude Code CLI
if ! command -v claude &>/dev/null; then
  echo "  Installing Claude Code CLI..."
  npm install -g @anthropic-ai/claude-code
else
  echo "  ✓ claude CLI already installed"
fi

echo "  ✓ All system dependencies ready"
echo ""

# ── Step 2: Authenticate GitHub CLI ──────────────────────────────────────────

echo "▸ Step 2/7: GitHub authentication..."

if ! gh auth status &>/dev/null; then
  echo "  GitHub CLI not authenticated. Logging in..."
  gh auth login --web --git-protocol https
else
  echo "  ✓ Already authenticated with GitHub"
fi
echo ""

# ── Step 3: Clone repositories ───────────────────────────────────────────────

echo "▸ Step 3/7: Cloning repositories..."

PROJECT_DIR="$HOME/view1-studio"

if [ -d "$PROJECT_DIR/.git" ]; then
  echo "  ✓ view1-studio already cloned, pulling latest..."
  cd "$PROJECT_DIR" && git pull origin main 2>/dev/null || true
else
  echo "  Cloning view1-studio..."
  gh repo clone kyletdow47/view1-studio "$PROJECT_DIR"
fi

# Also clone photo-sorter for the dashboard
PHOTO_DIR="$HOME/photo-sorter"
if [ -d "$PHOTO_DIR/.git" ]; then
  echo "  ✓ photo-sorter already cloned, pulling latest..."
  cd "$PHOTO_DIR" && git pull origin main 2>/dev/null || true
else
  echo "  Cloning photo-sorter..."
  gh repo clone kyletdow47/photo-sorter "$PHOTO_DIR"
fi

echo ""

# ── Step 4: Install Node dependencies ────────────────────────────────────────

echo "▸ Step 4/7: Installing Node dependencies..."

cd "$PROJECT_DIR"
npm install 2>/dev/null

cd "$PROJECT_DIR/agents/telegram-bot"
npm install 2>/dev/null

echo "  ✓ Dependencies installed"
echo ""

# ── Step 5: Configure environment ────────────────────────────────────────────

echo "▸ Step 5/7: Configuring environment..."

BOT_ENV="$PROJECT_DIR/agents/telegram-bot/.env"

if [ -f "$BOT_ENV" ] && grep -q "TELEGRAM_BOT_TOKEN=." "$BOT_ENV" 2>/dev/null; then
  echo "  ✓ Bot .env already configured"
else
  echo "  Setting up Telegram bot configuration..."
  echo ""

  read -p "  Enter your Telegram Bot Token (from @BotFather): " BOT_TOKEN
  read -p "  Enter your Telegram Chat ID: " CHAT_ID
  read -p "  Enter your Anthropic API Key: " ANTHROPIC_KEY

  cat > "$BOT_ENV" << ENVEOF
# View1 Studio — Telegram Bot Configuration
# Generated by mac-mini-bootstrap.sh on $(date)

TELEGRAM_BOT_TOKEN=$BOT_TOKEN
TELEGRAM_CHAT_ID=$CHAT_ID
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
PROJECT_DIR=$PROJECT_DIR
AGENTS_DIR=$PROJECT_DIR/agents
RESULTS_DIR=$PROJECT_DIR/agents/results
API_PORT=3847
ENVEOF

  echo "  ✓ Bot .env configured"
fi

# Ensure results directory exists
mkdir -p "$PROJECT_DIR/agents/results"
mkdir -p "$PROJECT_DIR/agents/tasks"

echo ""

# ── Step 6: Start the Telegram bot in tmux ───────────────────────────────────

echo "▸ Step 6/7: Starting Telegram bot..."

# Kill existing bot session if running
tmux kill-session -t view1-bot 2>/dev/null || true

# Start bot in a persistent tmux session
tmux new-session -d -s view1-bot -c "$PROJECT_DIR/agents/telegram-bot"
tmux send-keys -t view1-bot "node bot.js" Enter

# Wait a moment for the bot to start
sleep 3

# Verify it's running
if tmux list-sessions 2>/dev/null | grep -q view1-bot; then
  echo "  ✓ Telegram bot running in tmux session 'view1-bot'"
  echo "  → Attach with: tmux attach -t view1-bot"
  echo "  → Detach with: Ctrl+B then D"
else
  echo "  ✗ Bot failed to start. Check logs:"
  echo "    tmux attach -t view1-bot"
  exit 1
fi
echo ""

# ── Step 7: Verify everything works ─────────────────────────────────────────

echo "▸ Step 7/7: Verification..."

echo "  Checking tmux sessions..."
tmux list-sessions 2>/dev/null

echo ""
echo "  Checking bot API..."
sleep 2
if curl -s http://localhost:3847/api/status >/dev/null 2>&1; then
  echo "  ✓ Bot API responding on port 3847"
else
  echo "  ⚠ Bot API not responding yet (may need a few more seconds)"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ✅ SETUP COMPLETE — Mac Mini is autonomous!            ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║                                                          ║"
echo "║  Open Telegram and send /status to your bot.             ║"
echo "║                                                          ║"
echo "║  Key commands:                                           ║"
echo "║    /status    — See all agent status                     ║"
echo "║    /agents    — Full roster of 22 agents                 ║"
echo "║    /launch    — Start an agent on a task                 ║"
echo "║    /delegate  — Assign task (auto-queues if busy)        ║"
echo "║    /chain     — Auto-launch agent B when A completes     ║"
echo "║    /prs       — List open PRs with approve/merge buttons ║"
echo "║    /approve N — Approve PR #N                            ║"
echo "║    /merge N   — Squash-merge PR #N                       ║"
echo "║    /health    — System health check                      ║"
echo "║                                                          ║"
echo "║  You can now close this terminal and leave.              ║"
echo "║  The bot runs in tmux and survives logout.               ║"
echo "║                                                          ║"
echo "║  To re-attach later: tmux attach -t view1-bot            ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Prevent sleep (keep Mac Mini awake) ──────────────────────────────────────

echo "▸ Bonus: Preventing Mac Mini from sleeping..."
sudo pmset -a disablesleep 1 2>/dev/null && echo "  ✓ Sleep disabled" || echo "  ⚠ Run manually: sudo pmset -a disablesleep 1"
echo ""
echo "Done. Go to Telegram and send /status to verify."
